title: 人生天地间，行行重行行
author: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Android技术个人博客: framework, app. 

twitter_username: 
github_username:  nketc

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%M-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
# theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
